version: '3.7'

services:

  db:
    build: ./database
    container_name: mysql_database
    ports:
      - "3306:3306"
    networks:
      redCycle:
        ipv4_address: 192.168.20.2

  frontend:
    build: ./frontend
    container_name: daw-frontend
    ports:
      - "8080:8080"
    networks:
      redCycle:
        ipv4_address: 192.168.20.3

  backend:
    build: ./backend
    container_name: daw-backend
    ports:
      - "80:80"
    networks:
      redCycle:
        ipv4_address: 192.168.20.4

networks:
  redCycle:
    ipam:
      config:
        - subnet: 192.168.20.0/24

