version: '3.7'

services:

  db:
    build: ./database
    container_name: mysql_database
    ports:
      - "3306:3306"
    networks:
      - my-network
  frontend:
    build: ./frontend
    container_name: daw-frontend
    ports:
      - "8080:8080"
    networks:
      - my-network

  backend:
    build: ./backend
    container_name: daw-backend
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

