version: '3.7'

services:
  db:
    build: ./database
    container_name: daw-db
    ports:
      - "3306:3306"
    networks:
      my-network:
        ipv4_address: 172.20.0.2  # Direcci贸n IP deseada para el servicio de la base de datos

  frontend:
    build: ./frontend
    container_name: daw-frontend
    ports:
      - "80:80"  # Cambiar el puerto del contenedor del frontend de 3000 a 80
    networks:
      my-network:
        ipv4_address: 172.20.0.3  # Direcci贸n IP deseada para el servicio de frontend

  backend:
    build: ./backend
    container_name: daw-backend
    ports:
      - "8080:80"  # Cambiar el puerto del host a 8080 para evitar conflictos con el frontend
    networks:
      my-network:
        ipv4_address: 172.20.0.4  # Direcci贸n IP deseada para el servicio de backend

  phpmyadmin:
    build: ./phpmyadmin  # Ruta al directorio donde se encuentra tu Dockerfile de phpMyAdmin
    container_name: daw-phpmyadmin  # Nombre del contenedor
    ports:
      - "8081:80"  # Puerto para acceder a phpMyAdmin desde el host
    networks:
      my-network:
        ipv4_address: 172.20.0.5  # Direcci贸n IP deseada para phpMyAdmin
        
networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
