# Utiliza la imagen oficial de phpMyAdmin
FROM phpmyadmin:5.2

# Establece el directorio de trabajo
WORKDIR /etc/phpmyadmin

# Expone el puerto 80 para acceder a phpMyAdmin
EXPOSE 80

# CMD ["apache2-foreground"] # No es necesario especificar este comando ya que la imagen oficial ya lo hace automáticamente
